version: '3'
services:

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      FABU_DB_HOST: mongo
    ports: 
      - "9898:9898"

  


  
